---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx-test
# description will be included in the image's metadata
description: Bazzite-dx with my tweaks. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-open

image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: bazzite-dx/fonts.yml
  - from-file: bazzite-dx/packages.yml
  - from-file: bazzite-dx/flatpaks.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
