---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue
# description will be included in the image's metadata
description: Universal Blue with my tweaks. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
  
  - type: dnf
    repos:
      cleanup: true
      copr:
        enable:
          - ublue-os/packages
    install:
      packages:
        - firewall-config
        - fuse-encfs
        - iwd
        - podman-compose
        - powertop
        - samba
        - setools-console
        - uupd
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks

  - type: brew
    auto-update: true # enable auto-updates
    update-interval: 6h
    auto-upgrade: true # enable auto-upgrades
    upgrade-interval: 6h
    brew-analytics: false # disable telemetry
    nofile-limits: true # increase nofile limits
  
  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub
      install:
        - ca.desrt.dconf-editor
        - com.github.PintaProject.Pinta
        - com.github.iwalton3.jellyfin-media-player
        - com.github.rafostar.Clapper
        - com.github.tchx84.Flatseal
        - com.github.wwmm.easyeffects
        - com.makemkv.MakeMKV
        - com.mattjakeman.ExtensionManager
        - com.visualstudio.code
        - dev.heppen.webapps
        - io.github.dvlv.boxbuddyrs
        - io.github.flattool.Ignition
        - io.github.flattool.Warehouse
        - io.missioncenter.MissionCenter
        - io.podman_desktop.PodmanDesktop
        - me.iepure.devtoolbox
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.FileRoller
        - org.gnome.Firmware
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.Papers
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.font-viewer
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - page.tesk.Refine
        - sh.loft.devpod
  
  - type: systemd
    system:
      disabled:
        - flatpak-system-update.timer
      enabled:
        - uupd.timer
  
  - type: script
    scripts:
      - theming.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

