---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-dx
# description will be included in the image's metadata
description: Bluefin-dx with my tweaks. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: fonts
    fonts:
      google-fonts:
        - Noto Sans
        - Noto Sans Mono
        - Noto Serif
      nerd-fonts:
        - FiraCode
  
  - type: dnf
    repos:
      cleanup: true
      copr:
        enable:
          - ublue-os/packages
    install:
      packages:
        - code
        - firewall-config
        - fuse-encfs
        - gnome-tweaks
        - iwd
        - podman-compose
        - powertop
        - samba
        - setools-console
        - uupd
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - google-noto-sans-balinese-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-sans-javanese-fonts
        - google-noto-sans-sundanese-fonts
        - FiraCode # don't add spaces or "Nerd Font" suffix.

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - ca.desrt.dconf-editor
        - com.github.iwalton3.jellyfin-media-player
        - com.github.wwmm.easyeffects
        - com.makemkv.MakeMKV
        - com.mattjakeman.ExtensionManager
        # - com.visualstudio.code
        - dev.heppen.webapps
      remove:
        - io.gitlab.adhami3310.Impression
        - org.gnome.Maps
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
  
  - type: script
    snippets:
      - sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/vscode.repo
    scripts:
      - theming.sh
  
  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

